### ISSUE TITLE
[Permission Request] Backport to 1.19.2

### ISSUE THREAD

**Issue by min2222** [JMilamber/Brass_Amber_BattleTowers#131]
hello. i'm a modder who mainly does porting/backporting of mods. As far as I know, this mod is skipping version 1.19.2. but 1.19.2 is still popular version. and lots of people still  play the version. So I would like to ask for your permission to backport this mod to 1.19.2 from 1.20.

**Comment by JMilamber** [comment]
Hi @min2222.
I would be fine with you doing that. 
Let's chat either here or on discord (im pretty easy find on our sever) about how that would work so that we are on the same page.

When I have a stable version for 1.20 I create a branch for 1.19.2 for you to use, either contributing to directly or forking to push to.

**Comment by Darkmega18** [comment]
oh good.
but wait... you skipped 1.19.2 on purpose? D:
