### ISSUE TITLE
Loading Freezes with unknown mod

### ISSUE THREAD

**Issue by TheEmeraldBee** [JMilamber/Brass_Amber_BattleTowers#65]
When loading a world, the loading process will freeze entirely. Not freezing the game or creating a crash report, but the world generation will completely pause.

**Comment by JMilamber** [comment]
Does it continue after the pause or do you have to Close the game? 

Please also find your logs folder and post the most recent log file in the folder after this bug occurs. 

If you need help finding the folder see: [EcoCity Minecraft Client logs locations](https://ecocitycraft.com/forum/wiki/minecraft-client-logs/)

**Comment by TheEmeraldBee** [comment]
[latest.log](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/8145608/latest.log)

Here is the log for this, the weird part is that the game never stops responding but also never continues. The log to me says nothing.

**Comment by TheEmeraldBee** [comment]
[2022-02-25-8.log](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/8145624/2022-02-25-8.log)
Corrected Log. That one was wrong

**Comment by JMilamber** [comment]
looked at the log and I have a few questions/ideas  sorry xD 

Ideas (apologies if any of these are things you have already checked, just going through all the possibilities)

- Have you allocated enough RAM to this instance? is seems like you have a lot of mods and Minecraft may just be running out of memory when trying to spawn in everything related to all of the mods. 
-  Was BattleTowers the most recent mod added,? If not what mod/mods were added before it? Ther may be a chance that BT has a direct conflict with one which I can check for.
- If BattleTowers is removed can you load/create a world correctly?

A final thought, 80% of the log is filled with errors for loading crafting recipes/loot tables that are from the mod Campful, but looking at the log it doesn't seem like you have the mod installed ( I may be wrong) so that may be the issue

**Comment by TheEmeraldBee** [comment]
I do have 10 gb allocated right now and it should be fine.

Answering your 2nd question, BattleTowers was the last mod I added and that seemed to start the issue.

And 3rd question, it worked when removing BattleTowers and then adding it back made it stop working.

PS. I did figure out the issue. It seemed to be a bad installation of forge. I sent the pack to one of my friends and every world he loaded worked. He sent it back to me and we haven't had problems.

So I'm not sure if BattleTowers changes a forge install at all, but if it does this might be a bug or just unlucky with a bad install from curse.

**Comment by JMilamber** [comment]
Ah okay, that's odd lol. Could be because BT is jarred on an older stable version of forge than the current stable one (36.2.0 vs the current 36.2.20) though that shouldn't make a difference since that version difference is just bug fixes. :/
Glad you could figure out the issue! I'll make sure the next bugfix/update to 1.16.5 is jarred on the most current stable forge release. (36.2.20) maybe that will prevent this in the future lol.
