### ISSUE TITLE
Out of bounds exception crash when golem dies

### ISSUE THREAD

**Issue by Red6785** [JMilamber/Brass_Amber_BattleTowers#72]
**Describe the bug**
Crash upon killing golem

**To Reproduce**
Things needed to reproduce the behavior:
1. Theres 69 so im just gonna not post all of them. 
2. 1.16.5 Forge 36.2.30
3. 1.6.0
[crash-2022-03-11_21.23.46-server.txt](https://github.com/BrassAmber-Mods/Brass_Amber_BattleTowers/files/8236949/crash-2022-03-11_21.23.46-server.txt)

4. No
5.  Singleplayer
6. OS: Mac

**Expected behavior**
The golem dies and the game moves on

Heres a crash log.

**Comment by Red6785** [comment]
no clue why the crash log is in the middle but

**Comment by JMilamber** [comment]
Looking at where the code crashed there are two options for why this occurred, please answer the questions below so i can narrow it down. 

What happened in-game just before the crash-
    Were you in creative or survival, and did you spawn the golem with the summon command or from putting 3 keys into the monolith?
    Did you run any commands just before killing him?

**Comment by Red6785** [comment]
I was in survival. I did not spawn it with keys, I spawned it with a spawn egg. I couldn't get the keys to drop oddly enough, but I don't think that's a bug, so if possible could you also clarify how the keys system works? Also I ran a command from being in creative first to get the egg then into survival.

**Comment by JMilamber** [comment]
Ah, yes. So the bug is because the monolith spans another unseen entity hen it spans the golem which the golem references later, that reference uses a getEntities call in code which returns an array, which happens to be empty when the golem has been spawned not using a monolith.

When you find a tower, you must break at least 2 spawners on each floor in order to unlock the chest on the floor.
Floors 5, 6, and 8 have a key in their chest (tough there is a bug currently which makes the 8th floor sometimes not have its key) 

Take the 3 keys to the roof of the tower, and right-click on the monolith that spawns up there with the keys in your hand.
It will consume the keys, and on adding the third one it will disappear and spawn the golem in. 

How did you get a spawn egg for the golem? 
If you need to spawn im that way just use "/summon ba_bt:land_golem"

**Comment by Red6785** [comment]
Ah, coincidentally, on all those floors I couldn't find either the spawner or the chest.  It was in the jei menu, and I used creative cheat mode to grab it. Alright, thanks for your time!

**Comment by JMilamber** [comment]
If it was a previously spawned tower (before updating to the most recent version of the mod) it would have been broken as some blocks were renamed in the update, so when Minecraft looks for the block it's spawns air where they should be instead.

If you generate a new tower by traveling to unloaded chunks it should load correctly :)
